### ISSUE TITLE
Development Branch:  Defining the initial operation mode for a given pcb?

### ISSUE THREAD

**Issue by hogthrob** [LibreSolar/MPPT-Charger_Software#15]
I tested t1a65442eef5a4ec2f190af2922469e6e80bb8254 on a LibreSolar board 0.10 (assumin this version is equivalent to the published board design in the 20A MPPT Charger github (which it is according to the board labels). Anyway, when I start the board in dark conditions, it seems the boots part kicks in and raises the voltage displayed on the OLED quickly to 28V, displayed  current and power also increased. 
Turns out the code runs the nanogrid mode and I overlooked it. 

Now comes the question
How can we decide which configuration is to be activated? This is very much related to the battery config issue #13. 

Are all boards able to run both the "nanogrid" mode or "solar" mode? Or is a board (at least for now) either one or the other? Then we could put it into the pcb definition (1). If both are valid choices for most boards, we should make it part of the user initial configuration (2) (which I am working on).  

If one of the two modes is "safe" we could also always use this one unless the runtime configuration configures the device operation mode to the other (3).

1) is easiest to implement. least flexible though if boards support multiple operations modes. Otherwise the way to go in my opinion. 
2) good when compiling, still would need runtime configuration for later changes
3) similar to 2) but requires no runtime configuration or compile time configuration for users of "safe" mode.

@martinjaeger, what do you think?

**Comment by martinjaeger** [comment]
Good point. I just see that I accidentally forgot to reset to MPPT charge controller mode. I am currently playing with the Nanogrid functionality.

Regarding your questions:
1. Each type of synchronous buck converters can be used as a boost converter aswell. So all MPPT chargers can be operated in nanogrid mode or as boost solar chargers with higher voltage battery connected to the solar input and solar panel at the output. So an option in the PCB config is not suitable.
2. Yes, makes sense.
3. I'm not completely sure if one configuration can be considered safe. Probably the classical MPPT operation as it only starts if a correct voltage is detected on both sides and does not "create" a voltage itself. But I think it would be better to force the user to choose one configuration.

How do you think should we define the initial configuration? Using something like `#define OPERATION_MODE_NANOGRID`?

I also realized that the functions `bat_calculate_soc` and `charger_state_machine` should not use ls_port, but instead e.g. a pointer `dcdc_port_t *bat_port = &ls_port;` as a battery can be at the high-side aswell (bicycle battery charging via 12V solar panel).

**Comment by martinjaeger** [comment]
Initial operation mode is now defined in `config.h`, as implemented in 112f36b08b5601f0589ff6dae10fd9f6d68d40e0.

Example:
`#define DCDC_MODE_INIT      MODE_MPPT_BUCK`
